name: FIT4110_lab03_mock
values:
  - key: env
    value: mock
  - key: baseUrl
    value: 'http://localhost:4010'
  - key: authToken
    value: lab-token
  - key: teamName
    value: team-iot
  - key: aiVisionMockUrl
    value: 'http://localhost:4011'
